export interface Peak {
  id: number;
  name: string;
  altitude: number; // 海拔高度（公尺）
  latitude: number; // 緯度
  longitude: number; // 經度
  range?: string; // 所屬山脈
  description?: string; // 山岳簡介與特色
  tags?: string[]; // 特殊標籤（五岳、十峻、三尖等）
  coordinateSource?: 'official' | 'peakvisor' | 'reference' | 'estimated'; // 座標資料來源
  badgeStyle?: 'yushan' | 'xueshan' | 'central-north' | 'central-mid' | 'central-south' | 'qilai' | 'volcano' | 'flower' | 'shengling' | 'ocean' | 'wuling'; // 徽章樣式
}

// 台灣百岳完整列表（依排名 1-100）
// 資料來源：台灣百岳俱樂部、內政部國土測繪中心
export const PEAKS: Peak[] = [
  // === 1-20 名：台灣之巔與險峻名山 ===
  {
    id: 1,
    name: '玉山主峰',
    altitude: 3952,
    latitude: 23.47,
    longitude: 120.9572,
    range: '玉山山脈',
    description: '台灣與東北亞第一高峰，五岳之首，台幣 1000 元鈔票背後的主角。',
    tags: ['五岳'],
    coordinateSource: 'peakvisor',
    badgeStyle: 'yushan'
  },
  {
    id: 2,
    name: '雪山主峰',
    altitude: 3886,
    latitude: 24.3832,
    longitude: 121.2317,
    range: '雪山山脈',
    description: '台灣第二高峰，擁有全台最完整的冰河「圈谷」遺跡。',
    tags: ['五岳'],
    coordinateSource: 'peakvisor',
    badgeStyle: 'xueshan'
  },
  {
    id: 3,
    name: '玉山東峰',
    altitude: 3869,
    latitude: 23.4706,
    longitude: 120.965,
    range: '玉山山脈',
    description: '十峻之首，三面斷崖，地勢險要，登頂需攀爬鐵鍊垂直岩壁。',
    tags: ['十峻'],
    coordinateSource: 'peakvisor',
    badgeStyle: 'yushan'
  },
  {
    id: 4,
    name: '玉山北峰',
    altitude: 3858,
    latitude: 23.4833,
    longitude: 120.95,
    range: '玉山山脈',
    description: '設有全台最高氣象站，是拍攝「玉山主峰」標準角度的地點。',
    coordinateSource: 'reference',
    badgeStyle: 'yushan'
  },
  {
    id: 5,
    name: '玉山南峰',
    altitude: 3844,
    latitude: 23.46,
    longitude: 120.95,
    range: '玉山山脈',
    description: '十峻之一，山體由漆黑的頁岩構成，尖銳如龍角。',
    tags: ['十峻'],
    coordinateSource: 'reference',
    badgeStyle: 'yushan'
  },
  {
    id: 6,
    name: '秀姑巒山',
    altitude: 3805,
    latitude: 23.48,
    longitude: 121.02,
    range: '中央山脈',
    description: '中央山脈最高峰，五岳之一，山容寬闊氣勢壯麗。',
    tags: ['五岳'],
    coordinateSource: 'peakvisor',
    badgeStyle: 'central-mid'
  },
  {
    id: 7,
    name: '馬博拉斯山',
    altitude: 3785,
    latitude: 23.68,
    longitude: 121.15,
    range: '中央山脈',
    description: '十峻之一，馬博橫斷的核心，山勢高聳且極難抵達。',
    tags: ['十峻'],
    coordinateSource: 'reference',
    badgeStyle: 'central-mid'
  },
  {
    id: 8,
    name: '南湖大山',
    altitude: 3742,
    latitude: 24.365,
    longitude: 121.43,
    range: '中央山脈',
    description: '五岳之一，具有「帝王之山」美譽，冰河圈谷景觀極為壯闊。',
    tags: ['五岳'],
    coordinateSource: 'peakvisor',
    badgeStyle: 'ocean'
  },
  {
    id: 9,
    name: '東小南山',
    altitude: 3711,
    latitude: 23.455,
    longitude: 120.968,
    range: '玉山山脈',
    description: '玉山群峰之一，位於南峰支稜，稜脊由碎石構成，緩起伏。',
    coordinateSource: 'estimated',
    badgeStyle: 'yushan'
  },
  {
    id: 10,
    name: '中央尖山',
    altitude: 3705,
    latitude: 24.2833,
    longitude: 121.28,
    range: '中央山脈',
    description: '三尖之首，金字塔形尖峰，被譽為「寶島第一尖」。',
    tags: ['三尖'],
    coordinateSource: 'reference',
    badgeStyle: 'central-north'
  },
  {
    id: 11,
    name: '雪山北峰',
    altitude: 3703,
    latitude: 24.3917,
    longitude: 121.2383,
    range: '雪山山脈',
    description: '位於聖稜線上，山頂視野極佳，有著名的小木屋（雪北避難小屋）。',
    coordinateSource: 'reference',
    badgeStyle: 'shengling'
  },
  {
    id: 12,
    name: '關山',
    altitude: 3668,
    latitude: 23.25,
    longitude: 120.95,
    range: '中央山脈',
    description: '十峻之一，南中央山脈最高峰，有「南台首岳」之稱。',
    tags: ['十峻'],
    coordinateSource: 'reference',
    badgeStyle: 'central-south'
  },
  {
    id: 13,
    name: '大水窟山',
    altitude: 3642,
    latitude: 23.48,
    longitude: 120.99,
    range: '中央山脈',
    description: '位於南二段中點，山勢平緩，下方有著名的高山湖泊大水窟池。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-south'
  },
  {
    id: 14,
    name: '南湖東峰',
    altitude: 3632,
    latitude: 24.3553,
    longitude: 121.4431,
    range: '中央山脈',
    description: '全山為碎石片構成，景觀荒涼奇特，為宜蘭縣最高峰。',
    coordinateSource: 'reference',
    badgeStyle: 'ocean'
  },
  {
    id: 15,
    name: '東郡大山',
    altitude: 3619,
    latitude: 23.63,
    longitude: 121.08,
    range: '中央山脈',
    description: '東郡山彙最高峰，偏遠荒僻，山頂有一等三角點。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-mid'
  },
  {
    id: 16,
    name: '奇萊北峰',
    altitude: 3607,
    latitude: 24.1167,
    longitude: 121.3333,
    range: '中央山脈',
    description: '一奇之首，十峻之一，以「黑色奇萊」聞名，山形尖銳險惡。',
    tags: ['十峻'],
    coordinateSource: 'reference',
    badgeStyle: 'qilai'
  },
  {
    id: 17,
    name: '向陽山',
    altitude: 3602,
    latitude: 23.28,
    longitude: 121.03,
    range: '中央山脈',
    description: '嘉明湖路線必經，有巨大的「向陽大崩壁」，晨曦時呈現金紅色。',
    coordinateSource: 'reference',
    badgeStyle: 'volcano'
  },
  {
    id: 18,
    name: '大劍山',
    altitude: 3594,
    latitude: 24.3583,
    longitude: 121.2167,
    range: '雪山山脈',
    description: '十峻之一，雪山山脈名山，以陡降、缺水、地形艱難著稱。',
    tags: ['十峻'],
    coordinateSource: 'reference',
    badgeStyle: 'central-north'
  },
  {
    id: 19,
    name: '雲峰',
    altitude: 3564,
    latitude: 23.52,
    longitude: 120.98,
    range: '中央山脈',
    description: '南二段名峰，山體龐大厚實，山頂視野遼闊。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-south'
  },
  {
    id: 20,
    name: '奇萊主山',
    altitude: 3560,
    latitude: 24.1,
    longitude: 121.32,
    range: '中央山脈',
    description: '奇萊連峰之一，雖不如北峰險峻，但依舊保有峻峭的石壁景觀。',
    coordinateSource: 'reference',
    badgeStyle: 'qilai'
  },

  // === 21-40 名：聖稜線與四秀精華 ===
  {
    id: 21,
    name: '馬利加南山',
    altitude: 3546,
    latitude: 23.65,
    longitude: 121.13,
    range: '中央山脈',
    description: '馬博橫斷上的奇峰，山頂巨石林立，形如城堡。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-mid'
  },
  {
    id: 22,
    name: '南湖北山',
    altitude: 3536,
    latitude: 24.4,
    longitude: 121.45,
    range: '中央山脈',
    description: '蘭陽溪發源地，是中央山脈最北端的百岳。',
    coordinateSource: 'estimated',
    badgeStyle: 'ocean'
  },
  {
    id: 23,
    name: '大雪山',
    altitude: 3530,
    latitude: 24.3667,
    longitude: 121.15,
    range: '雪山山脈',
    description: '雪山西南稜核心，擁有非常廣闊的高山草原與冷杉林。',
    coordinateSource: 'reference',
    badgeStyle: 'xueshan'
  },
  {
    id: 24,
    name: '品田山',
    altitude: 3524,
    latitude: 24.3833,
    longitude: 121.2667,
    range: '雪山山脈',
    description: '武陵四秀之首，十峻之一，以驚險的「品田斷崖」聞名。',
    tags: ['十峻', '武陵四秀'],
    coordinateSource: 'reference',
    badgeStyle: 'shengling'
  },
  {
    id: 25,
    name: '玉山西峰',
    altitude: 3518,
    latitude: 23.465,
    longitude: 120.94,
    range: '玉山山脈',
    description: '稜線平緩，山頂掩映在冷杉林中，保留有日治時期的山神廟。',
    coordinateSource: 'reference',
    badgeStyle: 'yushan'
  },
  {
    id: 26,
    name: '頭鷹山',
    altitude: 3510,
    latitude: 24.35,
    longitude: 121.18,
    range: '雪山山脈',
    description: '山形遠觀酷似頭鷹俯瞰，位於大雪山與大霸尖山之間。',
    coordinateSource: 'estimated',
    badgeStyle: 'shengling'
  },
  {
    id: 27,
    name: '三叉山',
    altitude: 3496,
    latitude: 23.30,
    longitude: 121.03,
    range: '中央山脈',
    description: '台灣最熱門百岳之一，因天使的眼淚「嘉明湖」位於山腳而聞名。',
    coordinateSource: 'reference',
    badgeStyle: 'volcano'
  },
  {
    id: 28,
    name: '大霸尖山',
    altitude: 3492,
    latitude: 24.4167,
    longitude: 121.1333,
    range: '雪山山脈',
    description: '三尖之一，酒桶狀奇特山形，為泰雅與賽夏族的聖山。',
    tags: ['三尖'],
    coordinateSource: 'peakvisor',
    badgeStyle: 'shengling'
  },
  {
    id: 29,
    name: '南湖南峰',
    altitude: 3475,
    latitude: 24.345,
    longitude: 121.425,
    range: '中央山脈',
    description: '南湖群峰中最艱難的一座，滿佈亂石與陡坡。',
    coordinateSource: 'estimated',
    badgeStyle: 'ocean'
  },
  {
    id: 30,
    name: '東巒大山',
    altitude: 3468,
    latitude: 23.7,
    longitude: 121.0,
    range: '中央山脈',
    description: '東郡山彙名山，擁有極致絕美的短箭竹草原坡。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-mid'
  },
  {
    id: 31,
    name: '無明山',
    altitude: 3451,
    latitude: 24.3,
    longitude: 121.25,
    range: '中央山脈',
    description: '十峻之一，位於北二段，以崩塌嚴重的「無明斷崖」著稱。',
    tags: ['十峻'],
    coordinateSource: 'estimated',
    badgeStyle: 'flower'
  },
  {
    id: 32,
    name: '巴巴山',
    altitude: 3449,
    latitude: 24.34,
    longitude: 121.42,
    range: '中央山脈',
    description: '位於南湖群峰最南端，與南湖南峰緊鄰，地形破碎。',
    coordinateSource: 'estimated',
    badgeStyle: 'ocean'
  },
  {
    id: 33,
    name: '馬西山',
    altitude: 3443,
    latitude: 23.66,
    longitude: 121.12,
    range: '中央山脈',
    description: '位於馬博橫斷與南二段交接處，山形渾圓。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-mid'
  },
  {
    id: 34,
    name: '北合歡山',
    altitude: 3422,
    latitude: 24.1833,
    longitude: 121.2667,
    range: '中央山脈',
    description: '合歡群峰最高峰，五、六月滿山紅毛杜鵑盛開，路徑清楚親民。',
    tags: ['合歡群峰'],
    coordinateSource: 'reference',
    badgeStyle: 'central-north'
  },
  {
    id: 35,
    name: '合歡東峰',
    altitude: 3421,
    latitude: 24.1417,
    longitude: 121.2833,
    range: '中央山脈',
    description: '位於合歡山莊旁，山勢陡峭，冬季是絕佳的賞雪勝地。',
    tags: ['合歡群峰'],
    coordinateSource: 'reference',
    badgeStyle: 'central-north'
  },
  {
    id: 36,
    name: '小霸尖山',
    altitude: 3418,
    latitude: 24.415,
    longitude: 121.135,
    range: '雪山山脈',
    description: '緊鄰大霸尖山，山頂狹小奇尖，攀登需極度注意平衡。',
    coordinateSource: 'reference',
    badgeStyle: 'shengling'
  },
  {
    id: 37,
    name: '合歡主峰',
    altitude: 3417,
    latitude: 24.1417,
    longitude: 121.2667,
    range: '中央山脈',
    description: '最容易親近的百岳之一，水泥步道直通山頂。',
    tags: ['合歡群峰'],
    coordinateSource: 'reference',
    badgeStyle: 'central-north'
  },
  {
    id: 38,
    name: '南玉山',
    altitude: 3383,
    latitude: 23.448,
    longitude: 120.955,
    range: '玉山山脈',
    description: '玉山群峰最南端，路程遙遠且須穿過漫長的小波浪箭竹海。',
    coordinateSource: 'estimated',
    badgeStyle: 'yushan'
  },
  {
    id: 39,
    name: '畢祿山',
    altitude: 3371,
    latitude: 24.15,
    longitude: 121.2,
    range: '中央山脈',
    description: '中橫四辣之一，以連續陡升的「畢祿斷崖」考驗登山者。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-north'
  },
  {
    id: 40,
    name: '卓社大山',
    altitude: 3369,
    latitude: 23.85,
    longitude: 121.08,
    range: '中央山脈',
    description: '干卓萬縱走最高峰，地處偏遠且有無數危險斷崖。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-south'
  },

  // === 41-60 名：縱走必經名峰 ===
  {
    id: 41,
    name: '奇萊南峰',
    altitude: 3358,
    latitude: 24.03,
    longitude: 121.28,
    range: '中央山脈',
    description: '屬於能高越嶺古道支線，擁有極大面積的柔美金黃草原。',
    coordinateSource: 'reference',
    badgeStyle: 'qilai'
  },
  {
    id: 42,
    name: '南雙頭山',
    altitude: 3356,
    latitude: 23.50,
    longitude: 121.00,
    range: '中央山脈',
    description: '位於南二段，山形有南北兩峰對峙，由此下山可達拉庫音溪。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-south'
  },
  {
    id: 43,
    name: '能高南峰',
    altitude: 3349,
    latitude: 24.02,
    longitude: 121.32,
    range: '中央山脈',
    description: '十峻之一，能高安東軍路線中最險峻的一段。',
    tags: ['十峻'],
    coordinateSource: 'estimated',
    badgeStyle: 'qilai'
  },
  {
    id: 44,
    name: '志佳陽大山',
    altitude: 3345,
    latitude: 24.37,
    longitude: 121.20,
    range: '雪山山脈',
    description: '早期攀登雪山的唯一路線，以單日垂直爬升 1700 公尺著稱。',
    coordinateSource: 'estimated',
    badgeStyle: 'wuling'
  },
  {
    id: 45,
    name: '白姑大山',
    altitude: 3341,
    latitude: 24.25,
    longitude: 121.05,
    range: '中央山脈',
    description: '十翠之一，中橫四辣之「特辣」，路程遙遠且充滿倒木與亂石。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-north'
  },
  {
    id: 46,
    name: '八通關山',
    altitude: 3335,
    latitude: 23.52,
    longitude: 120.95,
    range: '中央山脈',
    description: '位於八通關古道上方，山頂為尖銳的石壁，展望極佳。',
    coordinateSource: 'reference',
    badgeStyle: 'volcano'
  },
  {
    id: 47,
    name: '新康山',
    altitude: 3331,
    latitude: 23.38,
    longitude: 121.10,
    range: '中央山脈',
    description: '十峻之一，東台第一霸，孤懸於中央山脈東側。',
    tags: ['十峻'],
    coordinateSource: 'reference',
    badgeStyle: 'volcano'
  },
  {
    id: 48,
    name: '丹大山',
    altitude: 3325,
    latitude: 23.78,
    longitude: 121.05,
    range: '中央山脈',
    description: '位於中央山脈中段，地理位置最深遠、最難到達的山岳之一。',
    coordinateSource: 'estimated',
    badgeStyle: 'volcano'
  },
  {
    id: 49,
    name: '桃山',
    altitude: 3325,
    latitude: 24.4,
    longitude: 121.27,
    range: '雪山山脈',
    description: '武陵四秀之一，山形遠觀如蜜桃，山頂視野 360 度無死角。',
    tags: ['武陵四秀'],
    coordinateSource: 'reference',
    badgeStyle: 'wuling'
  },
  {
    id: 50,
    name: '佳陽山',
    altitude: 3314,
    latitude: 24.33,
    longitude: 121.23,
    range: '雪山山脈',
    description: '大小劍線名山，山頭有一片巨大的斜板岩壁，非常有辨識度。',
    coordinateSource: 'estimated',
    badgeStyle: 'wuling'
  },
  {
    id: 51,
    name: '火石山',
    altitude: 3310,
    latitude: 24.36,
    longitude: 121.17,
    range: '雪山山脈',
    description: '雪山西南稜名峰，山體由黑色焦石堆疊，看似被火燒過。',
    coordinateSource: 'estimated',
    badgeStyle: 'xueshan'
  },
  {
    id: 52,
    name: '池有山',
    altitude: 3303,
    latitude: 24.39,
    longitude: 121.26,
    range: '雪山山脈',
    description: '武陵四秀之一，以山徑上的「池有石瀑」與「新達池」聞名。',
    tags: ['武陵四秀'],
    coordinateSource: 'reference',
    badgeStyle: 'wuling'
  },
  {
    id: 53,
    name: '伊澤山',
    altitude: 3297,
    latitude: 24.43,
    longitude: 121.15,
    range: '雪山山脈',
    description: '大霸群峰之一，是觀賞大霸尖山北側山壁的最佳位置。',
    coordinateSource: 'estimated',
    badgeStyle: 'shengling'
  },
  {
    id: 54,
    name: '卑南主山',
    altitude: 3295,
    latitude: 23.15,
    longitude: 120.98,
    range: '中央山脈',
    description: '中央山脈南段（南一段）的最後一座百岳。',
    coordinateSource: 'estimated',
    badgeStyle: 'ocean'
  },
  {
    id: 55,
    name: '干卓萬山',
    altitude: 3284,
    latitude: 23.87,
    longitude: 121.05,
    range: '中央山脈',
    description: '以危險的「干卓萬斷崖」聞名，是進階登山者的挑戰目標。',
    coordinateSource: 'estimated',
    badgeStyle: 'volcano'
  },
  {
    id: 56,
    name: '太魯閣大山',
    altitude: 3283,
    latitude: 24.17,
    longitude: 121.48,
    range: '中央山脈',
    description: '奇萊東稜最高峰，山形厚實廣大，容易迷路。',
    coordinateSource: 'estimated',
    badgeStyle: 'qilai'
  },
  {
    id: 57,
    name: '轆轆山',
    altitude: 3279,
    latitude: 23.48,
    longitude: 120.96,
    range: '中央山脈',
    description: '位於南二段，山形奇特，山頂有兩座並列的尖峰。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-south'
  },
  {
    id: 58,
    name: '喀西帕南山',
    altitude: 3276,
    latitude: 23.62,
    longitude: 121.17,
    range: '中央山脈',
    description: '馬博橫斷的最後一座山，展望可及花東縱谷。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-mid'
  },
  {
    id: 59,
    name: '內嶺爾山',
    altitude: 3275,
    latitude: 23.35,
    longitude: 121.08,
    range: '中央山脈',
    description: '位於新康橫斷，山勢平緩，是百岳中較冷門的高山。',
    coordinateSource: 'estimated',
    badgeStyle: 'wuling'
  },
  {
    id: 60,
    name: '鈴鳴山',
    altitude: 3272,
    latitude: 24.25,
    longitude: 121.23,
    range: '中央山脈',
    description: '北二段名山，山坡多為淺草坡，路徑優美。',
    coordinateSource: 'estimated',
    badgeStyle: 'flower'
  },

  // === 61-80 名：深邃山域與森林秘境 ===
  {
    id: 61,
    name: '郡大山',
    altitude: 3265,
    latitude: 23.62,
    longitude: 120.92,
    range: '中央山脈',
    description: '「坐車比爬山累」的代表，搭接駁車可直達 2800m 處。',
    coordinateSource: 'reference',
    badgeStyle: 'central-mid'
  },
  {
    id: 62,
    name: '能高山',
    altitude: 3262,
    latitude: 24.05,
    longitude: 121.30,
    range: '中央山脈',
    description: '早期東西向電路輸送的關鍵點，山容雄偉，視野寬闊。',
    coordinateSource: 'reference',
    badgeStyle: 'qilai'
  },
  {
    id: 63,
    name: '萬東乙山',
    altitude: 3258,
    latitude: 24.00,
    longitude: 121.33,
    range: '中央山脈',
    description: '亦稱火山，位於能高安東軍路線，山頂多為白碎石。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-mid'
  },
  {
    id: 64,
    name: '劍山',
    altitude: 3253,
    latitude: 24.34,
    longitude: 121.22,
    range: '雪山山脈',
    description: '大小劍線最遠的一座，因不提供三角點且極度陡峭，被戲稱「推拿山」。',
    coordinateSource: 'estimated',
    badgeStyle: 'wuling'
  },
  {
    id: 65,
    name: '屏風山',
    altitude: 3250,
    latitude: 24.23,
    longitude: 121.30,
    range: '中央山脈',
    description: '中橫四辣之「超辣」，路徑極陡，山壁如屏風般屹立。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-north'
  },
  {
    id: 66,
    name: '小關山',
    altitude: 3249,
    latitude: 23.23,
    longitude: 120.96,
    range: '中央山脈',
    description: '南一段名山，山勢險惡，多崩塌地形。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-south'
  },
  {
    id: 67,
    name: '義西請馬至山',
    altitude: 3245,
    latitude: 23.73,
    longitude: 121.08,
    range: '中央山脈',
    description: '位於丹大山域，是全台最難抵達的「荒野之心」。',
    coordinateSource: 'estimated',
    badgeStyle: 'volcano'
  },
  {
    id: 68,
    name: '牧山',
    altitude: 3241,
    latitude: 23.84,
    longitude: 121.06,
    range: '中央山脈',
    description: '位於干卓萬山群，山頂有座碧綠清澈的小水池。',
    coordinateSource: 'estimated',
    badgeStyle: 'flower'
  },
  {
    id: 69,
    name: '玉山前峰',
    altitude: 3239,
    latitude: 23.485,
    longitude: 120.95,
    range: '玉山山脈',
    description: '玉山群峰中最輕鬆的一座，但也有一段著名的亂石坡。',
    coordinateSource: 'reference',
    badgeStyle: 'yushan'
  },
  {
    id: 70,
    name: '石門山',
    altitude: 3237,
    latitude: 24.15,
    longitude: 121.28,
    range: '中央山脈',
    description: '「最簡單百岳」，位於合歡山公路旁，走路 20 分鐘即可登頂。',
    tags: ['合歡群峰'],
    coordinateSource: 'reference',
    badgeStyle: 'central-north'
  },
  {
    id: 71,
    name: '無雙山',
    altitude: 3231,
    latitude: 24.27,
    longitude: 121.22,
    range: '中央山脈',
    description: '無雙橫斷的考驗，以「無雙三連峰」的高難度地形著稱。',
    coordinateSource: 'estimated',
    badgeStyle: 'volcano'
  },
  {
    id: 72,
    name: '塔關山',
    altitude: 3222,
    latitude: 23.22,
    longitude: 120.93,
    range: '中央山脈',
    description: '南橫三星之一，就在南橫公路旁，岩壁陡峭但路程短。',
    tags: ['南橫三星'],
    coordinateSource: 'reference',
    badgeStyle: 'central-south'
  },
  {
    id: 73,
    name: '馬比杉山',
    altitude: 3211,
    latitude: 24.37,
    longitude: 121.47,
    range: '中央山脈',
    description: '位於南湖群峰最東側，需穿越溪谷與箭竹林，單日往返辛苦。',
    coordinateSource: 'estimated',
    badgeStyle: 'ocean'
  },
  {
    id: 74,
    name: '達芬尖山',
    altitude: 3208,
    latitude: 23.2939,
    longitude: 121.0686,
    range: '中央山脈',
    description: '三尖中最矮的一座，山形細長如手指，位於南二段。',
    tags: ['三尖'],
    coordinateSource: 'estimated',
    badgeStyle: 'volcano'
  },
  {
    id: 75,
    name: '雪山東峰',
    altitude: 3201,
    latitude: 24.38,
    longitude: 121.25,
    range: '雪山山脈',
    description: '雪主路線必經，山頂可俯覽武陵農場與群山展望。',
    coordinateSource: 'reference',
    badgeStyle: 'xueshan'
  },
  {
    id: 76,
    name: '南華山',
    altitude: 3184,
    latitude: 24.04,
    longitude: 121.27,
    range: '中央山脈',
    description: '亦稱能高北峰，全山覆蓋如地毯般的綠草坡。',
    coordinateSource: 'reference',
    badgeStyle: 'flower'
  },
  {
    id: 77,
    name: '關山嶺山',
    altitude: 3176,
    latitude: 23.24,
    longitude: 120.94,
    range: '中央山脈',
    description: '南橫三星之一，位於大關山隧道口，交通最便利的百岳之一。',
    tags: ['南橫三星'],
    coordinateSource: 'reference',
    badgeStyle: 'central-south'
  },
  {
    id: 78,
    name: '海諾南山',
    altitude: 3175,
    latitude: 23.20,
    longitude: 121.00,
    range: '中央山脈',
    description: '位於南一段，擁有極其寬廣平坦的高山草坡。',
    coordinateSource: 'estimated',
    badgeStyle: 'ocean'
  },
  {
    id: 79,
    name: '中雪山',
    altitude: 3173,
    latitude: 24.32,
    longitude: 121.13,
    range: '雪山山脈',
    description: '位於大雪山稜脈，因林相茂密且無水源，是登山者的耐力挑戰。',
    coordinateSource: 'estimated',
    badgeStyle: 'xueshan'
  },
  {
    id: 80,
    name: '閂山',
    altitude: 3168,
    latitude: 24.28,
    longitude: 121.27,
    range: '中央山脈',
    description: '位於北二段，山徑平易近人，以高山展望和草原聞名。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-north'
  },

  // === 81-100 名：壯闊草原與南方門戶 ===
  {
    id: 81,
    name: '甘薯峰',
    altitude: 3158,
    latitude: 24.30,
    longitude: 121.28,
    range: '中央山脈',
    description: '位於北二段，山名親民但路徑極辣，常與閂山連走。',
    coordinateSource: 'estimated',
    badgeStyle: 'flower'
  },
  {
    id: 82,
    name: '合歡山西峰',
    altitude: 3145,
    latitude: 24.13,
    longitude: 121.25,
    range: '中央山脈',
    description: '以「七上八下」的假山頭著稱，被譽為合歡群峰中的「鳥山」。',
    tags: ['合歡群峰'],
    coordinateSource: 'reference',
    badgeStyle: 'central-north'
  },
  {
    id: 83,
    name: '庫哈諾辛山',
    altitude: 3115,
    latitude: 23.26,
    longitude: 120.96,
    range: '中央山脈',
    description: '南橫三星之一，是通往關山的重要營地所在。',
    tags: ['南橫三星'],
    coordinateSource: 'reference',
    badgeStyle: 'central-south'
  },
  {
    id: 84,
    name: '加利山',
    altitude: 3112,
    latitude: 24.45,
    longitude: 121.12,
    range: '雪山山脈',
    description: '大霸尖山稜脈最南端，山勢平緩，是看大霸夕照的好地方。',
    coordinateSource: 'estimated',
    badgeStyle: 'shengling'
  },
  {
    id: 85,
    name: '白石山',
    altitude: 3110,
    latitude: 24.01,
    longitude: 121.35,
    range: '中央山脈',
    description: '能高安東軍路線的核心，山頂旁有如寶石般透明的白石池。',
    coordinateSource: 'estimated',
    badgeStyle: 'qilai'
  },
  {
    id: 86,
    name: '帕托魯山',
    altitude: 3101,
    latitude: 24.15,
    longitude: 121.45,
    range: '中央山脈',
    description: '奇萊東稜名山，山頭覆蓋濃密的箭竹林與倒木。',
    coordinateSource: 'estimated',
    badgeStyle: 'qilai'
  },
  {
    id: 87,
    name: '北大武山',
    altitude: 3092,
    latitude: 22.71,
    longitude: 120.83,
    range: '中央山脈',
    description: '五岳之一，南台灣唯一百岳，擁有絕美的雲海與鐵杉林景觀。',
    tags: ['五岳'],
    coordinateSource: 'peakvisor',
    badgeStyle: 'central-south'
  },
  {
    id: 88,
    name: '西巒大山',
    altitude: 3081,
    latitude: 23.65,
    longitude: 120.97,
    range: '中央山脈',
    description: '昔日伐木中心，路徑筆直向上毫無喘息空間，人稱「膝軟大山」。',
    coordinateSource: 'reference',
    badgeStyle: 'central-south'
  },
  {
    id: 89,
    name: '立霧主山',
    altitude: 3070,
    latitude: 24.12,
    longitude: 121.42,
    range: '中央山脈',
    description: '奇萊東稜名山，山體由巨大的白色大理石構成。',
    coordinateSource: 'estimated',
    badgeStyle: 'qilai'
  },
  {
    id: 90,
    name: '安東軍山',
    altitude: 3068,
    latitude: 23.98,
    longitude: 121.37,
    range: '中央山脈',
    description: '擁有最密集的台灣高山湖泊群。',
    coordinateSource: 'estimated',
    badgeStyle: 'qilai'
  },
  {
    id: 91,
    name: '光頭山',
    altitude: 3060,
    latitude: 24.06,
    longitude: 121.29,
    range: '中央山脈',
    description: '亦稱能高主峰北側山頭，山頂有一座著名的白色聖母像。',
    coordinateSource: 'estimated',
    badgeStyle: 'flower'
  },
  {
    id: 92,
    name: '巴紗乃魯山',
    altitude: 3060,
    latitude: 23.63,
    longitude: 121.14,
    range: '中央山脈',
    description: '位於馬博橫斷支線，地理位置極深。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-mid'
  },
  {
    id: 93,
    name: '九華山',
    altitude: 3060,
    latitude: 23.76,
    longitude: 121.06,
    range: '中央山脈',
    description: '位於丹大山域，地處中央山脈最偏遠的地區之一。',
    coordinateSource: 'estimated',
    badgeStyle: 'wuling'
  },
  {
    id: 94,
    name: '喀拉業山',
    altitude: 3133,
    latitude: 24.42,
    longitude: 121.25,
    range: '雪山山脈',
    description: '武陵四秀最末，因四周皆在樹林內無展望，被稱為百岳「四大鳥山」。',
    tags: ['武陵四秀'],
    coordinateSource: 'estimated',
    badgeStyle: 'wuling'
  },
  {
    id: 95,
    name: '布拉克桑山',
    altitude: 3036,
    latitude: 23.33,
    longitude: 121.09,
    range: '中央山脈',
    description: '位於新康橫斷，以漫長的箭竹海與枯燥的路徑著稱。',
    coordinateSource: 'estimated',
    badgeStyle: 'wuling'
  },
  {
    id: 96,
    name: '駒盆山',
    altitude: 3022,
    latitude: 23.42,
    longitude: 120.97,
    range: '中央山脈',
    description: '位於南二段，山頭平緩不起眼，是百岳中最矮的山頭之一。',
    coordinateSource: 'estimated',
    badgeStyle: 'volcano'
  },
  {
    id: 97,
    name: '六順山',
    altitude: 2999,
    latitude: 23.29,
    longitude: 121.04,
    range: '中央山脈',
    description: '早期標高超過三千，後測量不滿三千，但保留百岳地位。',
    coordinateSource: 'estimated',
    badgeStyle: 'wuling'
  },
  {
    id: 98,
    name: '南湖南山',
    altitude: 3475,
    latitude: 24.34,
    longitude: 121.42,
    range: '中央山脈',
    description: '南湖山群之一，地形破碎多岩石。',
    coordinateSource: 'estimated',
    badgeStyle: 'ocean'
  },
  {
    id: 99,
    name: '鹿山',
    altitude: 2981,
    latitude: 23.44,
    longitude: 120.95,
    range: '玉山山脈',
    description: '玉山後四峰之一，是 100 座百岳中高度最低的，路程極度辛苦。',
    coordinateSource: 'estimated',
    badgeStyle: 'central-south'
  },
  {
    id: 100,
    name: '南湖東南峰',
    altitude: 3462,
    latitude: 24.3553,
    longitude: 121.4431,
    range: '中央山脈',
    description: '南湖群峰之一，需穿越複雜地形。',
    coordinateSource: 'estimated',
    badgeStyle: 'volcano'
  }
];

export const TOTAL_PEAKS = 100; // 台灣百岳總數
export const DEMO_PEAKS_COUNT = PEAKS.length; // 當前資料數量（應為100）
